version: 0.2

phases:
  pre_build:
    commands:
      - docker-compose pull --ignore-pull-failures 
  build:
    commands:
      - docker-compose build 
  post_build:
    commands:
      - docker-compose up